#!/usr/bin/env bash

cmake \
	-S llvm \
	-B build \
	-G 'Ninja' \
	-DLLVM_ENABLE_PROJECTS='compiler-rt;libc' \
	-DLLVM_ENABLE_RUNTIME='libcxx;libcxxabi;libunwind;lld' \
	-DCLANG_DEFAULT_LINKER=lld \
	-DLLVM_ENABLE_ASSERTIONS=OFF \
	-DLLVM_PARALLEL_LINK_JOBS=1 \
	-DLLVM_PARALLEL_COMPILE_JOBS=1 \
	-DLLVM_TARGETS_TO_BUILD=host \
	-DCLANG_ENABLE_STATIC_ANALYZER=OFF \
	-DLLVM_USE_SPLIT_DWRARF=ON \
	-DBUILD_SHARED_LIBS=ON \
	-DLLVM_CCACHE_BUILD=ON \
	-DLLVM_ENABLE_PEDANTIC=OFF \
	-DLLVM_INCLUDE_BENCHMARKS=OFF \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DCMAKE_BUILD_TYPE=MinSizeRel

